Repository snu-quiqcl/iquip, pull requests merged in 2023-10, with the labels that each got.

#183 Periodic synchronization (polling) of realtime dataset
  iquip/apps/dataviewer.py
Labels: enhancement

#178 Single DDS controller: `DDSControllerWidget`
  iquip/apps/monitor.py
Labels: enhancement

#184 Scheduler: Construct the model/view architecture
  iquip/apps/scheduler.py
  iquip/protocols.py
  tests/test_scheduler.py
Labels: enhancement

#190 Apply `qiwis` v2.2.0
  .github/workflows/pylint.yml
  .github/workflows/unittest.yml
  config_template.json
  iquip/apps/explorer.py
  tests/test_explorer.py
Labels: enhancement

#189 Set default index -1
  iquip/apps/dataviewer.py
Labels: enhancement

#187 DDS contoller frame and functions to control DDSs
  config_template.json
  iquip/apps/monitor.py
Labels: enhancement

#195 Add auto range checkbox
  iquip/apps/dataviewer.py
Labels: enhancement

#191 Scheduler: Fetch the actual scheduled queue and apply it in the view
  iquip/apps/scheduler.py
Labels: enhancement

#197 Scheduler: Enable to delete and terminate a specific experiment
  iquip/apps/scheduler.py
Labels: enhancement

#196 Highlight selected data point
  iquip/apps/dataviewer.py
Labels: enhancement

#199 Codes for log viewer cursor reset
  iquip/apps/logger.py
Labels: bug

#202 Fetching schedule stops permanently after an error occurs
  iquip/apps/scheduler.py
Labels: bug

#204 Convert negative index to positive in `dataPoint()`
  iquip/apps/dataviewer.py
Labels: bug

#208 Modification based dataset realtime update
  iquip/apps/dataviewer.py
Labels: enhancement

#212 Safe fetcher thread
  iquip/apps/dataviewer.py
Labels: bug, enhancement

#211 Enable to open the builder by double-clicking a file entry
  iquip/apps/explorer.py
  tests/test_explorer.py
Labels: enhancement

#214 Improve thread signals and slots
  iquip/apps/builder.py
  iquip/apps/explorer.py
  iquip/apps/monitor.py
  iquip/apps/result_explorer.py
  iquip/apps/scheduler.py
  iquip/apps/thread.py
  tests/test_builder.py
  tests/test_explorer.py
Labels: enhancement, refactor
