Repository snu-quiqcl/iquip, pull requests merged in 2023-08, with the labels that each got.

#69 Giwon2004/63/scheduler
  iquip/apps/builder.py
  iquip/apps/explorer.py
  iquip/apps/scheduler.py
  iquip/apps/thread.py
  setup.json
Labels: enhancement

#82 Implement additional functions of the builder
  iquip/apps/builder.py
  iquip/apps/explorer.py
  tests/test_builder.py
Labels: enhancement

#95 BUG: Click open button of explorer without selecting any item
  iquip/apps/explorer.py
  tests/test_explorer.py
Labels: bug

#86 Implement the left unit tests for builder app
  iquip/apps/builder.py
  tests/test_builder.py
  tests/test_explorer.py
Labels: test

#99 Handle an empty `choice`s of enumeration value
  iquip/apps/builder.py
  setup.json
Labels: enhancement

#101 Add `logger` back
  iquip/apps/builder.py
  iquip/apps/explorer.py
  iquip/apps/thread.py
  setup.json
Labels: bug

#88 Aijuh/76/logs to file
  iquip/apps/logger.py
  setup.json
Labels: enhancement

#89 Unit test for scheduler
  tests/test_scheduler.py
Labels: enhancement

#104 Change information holder to `SubmittedExperimentInfo`
  iquip/apps/scheduler.py
  iquip/protocols.py
  tests/test_scheduler.py
Labels: enhancement, style

#92 Unit test for logger App
  tests/test_logger.py
Labels: test

#108 fix setup.json
  setup.json
Labels: bug

#110 Match 3.8 Python supports
  iquip/protocols.py
Labels: style

#105 Implement the functional tests for the builder app
  tests/test_builder.py
Labels: test
