Repository snu-quiqcl/iquip, pull requests merged in 2023-09, with the labels that each got.

#113 Update unittest for logger.py
  tests/test_logger.py
Labels: enhancement

#111 Add menu for queued experiments
  iquip/apps/scheduler.py
  iquip/protocols.py
  tests/test_scheduler.py
Labels: enhancement

#118 Add `order` option to `SubmittedExperimentInfo`
  iquip/protocols.py
Labels: enhancement

#117 Add a result explorer
  iquip/apps/result_explorer.py
  setup.json
Labels: enhancement

#91 Fetch from the proxy server
  iquip/apps/scheduler.py
Labels: enhancement

#125 `NDArrayViewer` and `CurvePlotViewer`
  .github/workflows/pylint.yml
  .github/workflows/unittest.yml
  iquip/apps/dataviewer.py
Labels: enhancement

#129 Set default value for `priority` and modify `sort`
  iquip/apps/scheduler.py
  iquip/protocols.py
Labels: bug

#131 Update the QIWIS version to 2.1.0
  .github/workflows/pylint.yml
  .github/workflows/unittest.yml
  config.json
  iquip/apps/builder.py
  iquip/apps/explorer.py
  iquip/apps/result_explorer.py
  iquip/apps/scheduler.py
  iquip/apps/thread.py
  resources/background.jpg
  resources/icon.jpg
Labels: enhancement, repository

#135 Fix the bug of unittest in SchedulerApp
  iquip/apps/scheduler.py
  tests/test_scheduler.py
Labels: bug, test

#138 Block opening the builder of a directory
  iquip/apps/explorer.py
Labels: bug

#140 Improve unit test output
  .github/workflows/unittest.yml
  tests/test_builder.py
Labels: enhancement, test

#139 `HistogramViewer` and `ImageViewer`
  iquip/apps/dataviewer.py
Labels: enhancement

#142 Kangz12345/141/config template
  .gitignore
  config_template.json
Labels: enhancement, repository

#147 Pass the unittest without any error
  tests/test_builder.py
  tests/test_explorer.py
  tests/test_scheduler.py
Labels: test

#146 Minimal `DataViewerApp` part 0: `SourceWidget`
  iquip/apps/dataviewer.py
Labels: enhancement

#120 Implement H5 result viewer
  .github/workflows/pylint.yml
  .github/workflows/unittest.yml
  iquip/apps/builder.py
  iquip/apps/result_explorer.py
  tests/test_builder.py
Labels: enhancement

#151 Minimal `DataViewerApp` part 1: `DataPointWidget`
  iquip/apps/dataviewer.py
Labels: enhancement

#156 Minimal `DataViewerApp` part 1-1: Histogram
  iquip/apps/dataviewer.py
Labels: enhancement

#157 Single TTL controller: `TTLControllerWidget`
  iquip/apps/monitor.py
Labels: enhancement

#158 Frame with all TTL controllers: `TTLControllerFrame`
  iquip/apps/monitor.py
Labels: enhancement

#160 Minimal `DataViewerApp` part 2: `MainPlotWidget`
  iquip/apps/dataviewer.py
Labels: enhancement

#161 Add functions to run actually: `DeviceMonitorApp`
  config_template.json
  iquip/apps/monitor.py
Labels: enhancement

#164 Minimal `DataViewerApp` part 3: Add frame
  iquip/apps/dataviewer.py
Labels: enhancement

#170 Use TTL device name instead of channel number
  config_template.json
  iquip/apps/monitor.py
Labels: enhancement

#166 DAC controller widget and frame
  iquip/apps/monitor.py
Labels: enhancement

#172 Add functions in terms of DAC to `DeviceMonitorApp`
  config_template.json
  iquip/apps/monitor.py
Labels: enhancement

#171 Minimal `DataViewerApp` part 3: Data policy
  iquip/apps/dataviewer.py
Labels: enhancement

#176 Minimal `DataViewerApp` part 4: Final
  config_template.json
  iquip/apps/dataviewer.py
Labels: enhancement
