Repository snu-quiqcl/iquip, pull requests merged in 2024-04, with the labels that each got.

#262 Fetch RID list in remote part
  iquip/apps/dataviewer.py
Labels: enhancement

#248 Threaded motorized stage manager
  .github/workflows/pylint.yml
  .github/workflows/unittest.yml
  iquip/apps/stage.py
Labels: enhancement

#270 Convert due date in ISO format
  iquip/apps/scheduler.py
Labels: enhancement

#267 Restart fetching schedule when the connection is lost
  iquip/apps/scheduler.py
Labels: bug

#268 Restart synchronizing TTL status when the connection is lost
  iquip/apps/monitor.py
Labels: enhancement

#271 Fetch dataset name list of selected RID in remote part
  iquip/apps/dataviewer.py
Labels: enhancement

#272 Restart to fetch dataset name list when connection is lost
  .pylintrc
  iquip/apps/dataviewer.py
Labels: enhancement

#273 Fetch selected dataset in remote mode
  iquip/apps/dataviewer.py
Labels: enhancement

#276 Improve builder UI compactly
  iquip/apps/builder.py
Labels: enhancement

#275 `StageWidget` to monitor and control each motorized stage
  iquip/apps/stage.py
Labels: enhancement

#280 Fix the bug that a normal websocket closing leaves an exception log
  iquip/apps/dataviewer.py
  iquip/apps/monitor.py
  iquip/apps/scheduler.py
Labels: bug

#282 Fancy TTL status
  iquip/apps/monitor.py
Labels: enhancement

#278 Fix a bug when changing the remote mode rapidly
  iquip/apps/dataviewer.py
Labels: bug

#285 Stage controller app
  config_template.json
  iquip/apps/stage.py
Labels: enhancement

#288 Update background image and icon
  config_template.json
  resources/background.jpg
  resources/background.png
  resources/icon.jpg
  resources/icon.png
Labels: enhancement

#290 Use `requirements.txt` instead of direct installation
  .github/workflows/pylint.yml
  .github/workflows/unittest.yml
  requirements.txt
Labels: repository

#295 Clear `scanListWidget` when reloaded
  iquip/apps/builder.py
Labels: bug

#297 Fix various bugs when fetching dataset name list
  iquip/apps/dataviewer.py
Labels: bug

#298 Catch the case where target device doesn't exist in monitor app
  iquip/apps/monitor.py
Labels: bug
